# Generated by Django 4.2.4 on 2023-08-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BottleCap',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('raw_materials', models.CharField(max_length=120)),
                ('application', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
                ('manufacturing_technology', models.CharField(max_length=120)),
                ('food_security', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='preforms')),
            ],
            options={
                'verbose_name': 'Bottle Cap',
                'verbose_name_plural': 'Bottle Caps',
            },
        ),
        migrations.CreateModel(
            name='Preform',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('thread_standard', models.CharField(max_length=120)),
                ('weight', models.IntegerField()),
                ('height', models.FloatField(null=True)),
                ('blown_volume', models.FloatField()),
                ('image', models.ImageField(upload_to='preforms')),
            ],
            options={
                'verbose_name': 'Preform',
                'verbose_name_plural': 'Preforms',
            },
        ),
    ]
