# Generated by Django 4.2.4 on 2023-08-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BottleCap',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='code')),
                ('raw_materials', models.CharField(max_length=120, verbose_name='Raw materials')),
                ('application', models.CharField(max_length=255, verbose_name='Application')),
                ('logo', models.CharField(max_length=255, verbose_name='Logo')),
                ('manufacturing_technology', models.CharField(max_length=120, verbose_name='Manufacturing technology')),
                ('food_security', models.CharField(max_length=255, verbose_name='Food security')),
                ('image', models.ImageField(upload_to='preforms', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Bottle Cap',
                'verbose_name_plural': 'Bottle Caps',
            },
        ),
        migrations.CreateModel(
            name='Preform',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='code')),
                ('thread_standard', models.CharField(max_length=120, verbose_name='Thread standard')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weight')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Height')),
                ('blown_volume', models.CharField(max_length=120, null=True, verbose_name='Blown volume')),
                ('image', models.ImageField(upload_to='preforms', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Preform',
                'verbose_name_plural': 'Preforms',
            },
        ),
    ]
