# Generated by Django 4.2.4 on 2023-09-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_alter_preform_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottlecap',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='title'),
        ),
    ]
