# Generated by Django 4.2.4 on 2023-09-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_bottlecap_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preform',
            name='blown_volume',
        ),
    ]
