# Generated by Django 4.2.4 on 2023-09-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_remove_preform_blown_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottlecap',
            name='manufacturing_technology',
        ),
        migrations.RenameField(
            model_name='preform',
            old_name='thread_standard',
            new_name='preform_size'
        ),
    ]
