# Generated by Django 4.2.4 on 2023-09-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='subtitle',
            field=models.TextField(default=' ', verbose_name='Subtitle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
    ]
