# Generated by Django 4.2.4 on 2023-09-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_banner_subtitle_alter_banner_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('image', models.ImageField(upload_to='about-us', verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
