# Generated by Django 4.2.4 on 2023-09-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_aboutpage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254, verbose_name='sender')),
                ('subject', models.CharField(max_length=120, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
            ],
        ),
    ]
